/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bdotimer;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Guilherme
 */
public class mainFrame extends javax.swing.JFrame {
        int width;
        int height;
        sTimer st01,st02,st03,st04,st05;
        startLessChecker slc;
        
    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        this.width = this.getWidth();
        this.height = this.getHeight();
        setupTimer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        tf01 = new javax.swing.JTextField();
        jlessCur = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtm01 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jts01 = new javax.swing.JTextField();
        jl01 = new javax.swing.JLabel();
        jtfCurLess = new javax.swing.JTextField();
        jl02 = new javax.swing.JLabel();
        tf02 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtm02 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jts02 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jl03 = new javax.swing.JLabel();
        tf03 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtm03 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jts03 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jl04 = new javax.swing.JLabel();
        tf04 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtm04 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jts04 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jl05 = new javax.swing.JLabel();
        tf05 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtm05 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jts05 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        jButton1.setText("Play");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tf01.setText("msg..");
        tf01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tf01MouseEntered(evt);
            }
        });

        jlessCur.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlessCur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlessCur.setText("00:00:00");

        jLabel3.setText("Mins:");

        jtm01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtm01.setText("13");
        jtm01.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtm01FocusLost(evt);
            }
        });
        jtm01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtm01MouseEntered(evt);
            }
        });

        jLabel4.setText("Secs:");

        jts01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jts01.setText("00");
        jts01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jts01MouseEntered(evt);
            }
        });

        jl01.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jl01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl01.setText("00:00:00");

        jtfCurLess.setText("Cur Close");
        jtfCurLess.setEnabled(false);
        jtfCurLess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtfCurLessMouseEntered(evt);
            }
        });

        jl02.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jl02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl02.setText("00:00:00");

        tf02.setText("msg..");
        tf02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tf02MouseEntered(evt);
            }
        });

        jLabel6.setText("Mins:");

        jtm02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtm02.setText("13");
        jtm02.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtm02FocusLost(evt);
            }
        });
        jtm02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtm02MouseEntered(evt);
            }
        });

        jLabel7.setText("Secs:");

        jts02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jts02.setText("00");
        jts02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jts02MouseEntered(evt);
            }
        });

        jButton2.setText("Play");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jl03.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jl03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl03.setText("00:00:00");

        tf03.setText("msg..");
        tf03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tf03MouseEntered(evt);
            }
        });

        jLabel8.setText("Mins:");

        jtm03.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtm03.setText("13");
        jtm03.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtm03FocusLost(evt);
            }
        });
        jtm03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtm03MouseEntered(evt);
            }
        });

        jLabel9.setText("Secs:");

        jts03.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jts03.setText("00");
        jts03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jts03MouseEntered(evt);
            }
        });

        jButton3.setText("Play");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jl04.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jl04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl04.setText("00:00:00");

        tf04.setText("msg..");
        tf04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tf04MouseEntered(evt);
            }
        });

        jLabel10.setText("Mins:");

        jtm04.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtm04.setText("13");
        jtm04.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtm04FocusLost(evt);
            }
        });
        jtm04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtm04MouseEntered(evt);
            }
        });

        jLabel11.setText("Secs:");

        jts04.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jts04.setText("00");
        jts04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jts04MouseEntered(evt);
            }
        });

        jButton4.setText("Play");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jl05.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jl05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl05.setText("00:00:00");

        tf05.setText("msg..");
        tf05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tf05MouseEntered(evt);
            }
        });

        jLabel12.setText("Mins:");

        jtm05.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtm05.setText("13");
        jtm05.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtm05FocusLost(evt);
            }
        });
        jtm05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtm05MouseEntered(evt);
            }
        });

        jLabel13.setText("Secs:");

        jts05.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jts05.setText("00");
        jts05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jts05MouseEntered(evt);
            }
        });

        jButton5.setText("Play");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jl03, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf03, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtm03, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jts03, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jl04, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf04, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtm04, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jts04, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlessCur, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCurLess, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jl01, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf01, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jl02, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf02, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtm01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jts01, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtm02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jts02, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jl05, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf05, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtm05, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jts05, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlessCur, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCurLess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(tf01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtm01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jts01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl01, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(tf02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtm02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jts02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl02, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(tf03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jtm03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jts03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl03, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(tf04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jtm04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jts04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl04, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(tf05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jtm05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jts05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl05, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        //width = this.getWidth();
        //height = this.getHeight();
        this.setSize(300, 80);
    }//GEN-LAST:event_formMouseExited

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        this.setSize(this.width,this.height);
    }//GEN-LAST:event_formMouseEntered

    private void tf01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf01MouseEntered
        // TODO add your handling code here:
        this.setSize(this.width,this.height);
    }//GEN-LAST:event_tf01MouseEntered

    private void jtm01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtm01MouseEntered
        // TODO add your handling code here:
        this.setSize(this.width,this.height);
    }//GEN-LAST:event_jtm01MouseEntered

    private void jts01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jts01MouseEntered
        // TODO add your handling code here:
        this.setSize(this.width,this.height);
    }//GEN-LAST:event_jts01MouseEntered

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        this.setSize(this.width,this.height);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jtfCurLessMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfCurLessMouseEntered
        // TODO add your handling code here:
        this.setSize(this.width,this.height);
    }//GEN-LAST:event_jtfCurLessMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!st01.isRunnig()){
            st01.start();
            if(!slc.isRunning()){
                slc = new startLessChecker(st01,st02,st03,st04,st05,jlessCur,jtfCurLess,tf01,tf02,tf03,tf04,tf05);
                slc.start();
            }else{
                slc.close();
                slc = new startLessChecker(st01,st02,st03,st04,st05,jlessCur,jtfCurLess,tf01,tf02,tf03,tf04,tf05);
                try{
                    Thread.sleep(100);
                } catch (InterruptedException ex) {
                    Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                slc.start();
            }
        }else{
            st01.stop();
            st01 = new sTimer(jl02,Integer.parseInt(jtm02.getText()),Integer.parseInt(jts02.getText()));
            slc.close();
            if(checkIfSomeoneIsRunning()){
                slc = new startLessChecker(st01,st02,st03,st04,st05,jlessCur,jtfCurLess,tf01,tf02,tf03,tf04,tf05);
                slc.start();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf02MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf02MouseEntered
        // TODO add your handling code here:
        this.setSize(this.width,this.height);
    }//GEN-LAST:event_tf02MouseEntered

    private void jtm02MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtm02MouseEntered
        // TODO add your handling code here:
        this.setSize(this.width,this.height);
    }//GEN-LAST:event_jtm02MouseEntered

    private void jts02MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jts02MouseEntered
        // TODO add your handling code here:
        this.setSize(this.width,this.height);
    }//GEN-LAST:event_jts02MouseEntered

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        this.setSize(this.width,this.height);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(!st02.isRunnig()){
            st02.start();
            if(!slc.isRunning()){
                slc = new startLessChecker(st01,st02,st03,st04,st05,jlessCur,jtfCurLess,tf01,tf02,tf03,tf04,tf05);
                slc.start();
            }else{
                slc.close();
                slc = new startLessChecker(st01,st02,st03,st04,st05,jlessCur,jtfCurLess,tf01,tf02,tf03,tf04,tf05);
                try{
                    Thread.sleep(100);
                } catch (InterruptedException ex) {
                    Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                slc.start();
            }
        }else{
            st02.stop();
            st02 = new sTimer(jl02,Integer.parseInt(jtm02.getText()),Integer.parseInt(jts02.getText()));
            slc.close();
            if(checkIfSomeoneIsRunning()){
                slc = new startLessChecker(st01,st02,st03,st04,st05,jlessCur,jtfCurLess,tf01,tf02,tf03,tf04,tf05);
                slc.start();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtm01FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtm01FocusLost
        // TODO add your handling code here:
        if(!st01.isRunnig()){
            st01.stop();
            st01 = new sTimer(jl01,Integer.parseInt(jtm01.getText()),Integer.parseInt(jts01.getText()));
        }
    }//GEN-LAST:event_jtm01FocusLost

    private void jtm02FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtm02FocusLost
        // TODO add your handling code here:
        if(!st02.isRunnig()){
            st02.stop();
            st02 = new sTimer(jl02,Integer.parseInt(jtm02.getText()),Integer.parseInt(jts02.getText()));
        }
    }//GEN-LAST:event_jtm02FocusLost

    private void tf03MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf03MouseEntered
        // TODO add your handling code here:
        this.setSize(this.width,this.height);
    }//GEN-LAST:event_tf03MouseEntered

    private void jtm03FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtm03FocusLost
        // TODO add your handling code here:
        if(!st03.isRunnig()){
            st03.stop();
            st03 = new sTimer(jl03,Integer.parseInt(jtm03.getText()),Integer.parseInt(jts03.getText()));
        }
    }//GEN-LAST:event_jtm03FocusLost

    private void jtm03MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtm03MouseEntered
        // TODO add your handling code here:
        this.setSize(this.width,this.height);
    }//GEN-LAST:event_jtm03MouseEntered

    private void jts03MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jts03MouseEntered
        // TODO add your handling code here:
        this.setSize(this.width,this.height);
    }//GEN-LAST:event_jts03MouseEntered

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
        this.setSize(this.width,this.height);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(!st03.isRunnig()){
            st03.start();
            if(!slc.isRunning()){
                slc = new startLessChecker(st01,st02,st03,st04,st05,jlessCur,jtfCurLess,tf01,tf02,tf03,tf04,tf05);
                slc.start();
            }else{
                slc.close();
                slc = new startLessChecker(st01,st02,st03,st04,st05,jlessCur,jtfCurLess,tf01,tf02,tf03,tf04,tf05);
                try{
                    Thread.sleep(100);
                } catch (InterruptedException ex) {
                    Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                slc.start();
            }
        }else{
            st03.stop();
            st03 = new sTimer(jl02,Integer.parseInt(jtm02.getText()),Integer.parseInt(jts02.getText()));
            slc.close();
            if(checkIfSomeoneIsRunning()){
                slc = new startLessChecker(st01,st02,st03,st04,st05,jlessCur,jtfCurLess,tf01,tf02,tf03,tf04,tf05);
                slc.start();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tf04MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf04MouseEntered
        // TODO add your handling code here:
        this.setSize(this.width,this.height);
    }//GEN-LAST:event_tf04MouseEntered

    private void jtm04FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtm04FocusLost
        // TODO add your handling code here:
        if(!st04.isRunnig()){
            st04.stop();
            st04 = new sTimer(jl04,Integer.parseInt(jtm04.getText()),Integer.parseInt(jts04.getText()));
        }
    }//GEN-LAST:event_jtm04FocusLost

    private void jtm04MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtm04MouseEntered
        // TODO add your handling code here:
        this.setSize(this.width,this.height);
    }//GEN-LAST:event_jtm04MouseEntered

    private void jts04MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jts04MouseEntered
        // TODO add your handling code here:
        this.setSize(this.width,this.height);
    }//GEN-LAST:event_jts04MouseEntered

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
        this.setSize(this.width,this.height);
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(!st04.isRunnig()){
            st04.start();
            if(!slc.isRunning()){
                slc = new startLessChecker(st01,st02,st03,st04,st05,jlessCur,jtfCurLess,tf01,tf02,tf03,tf04,tf05);
                slc.start();
            }else{
                slc.close();
                slc = new startLessChecker(st01,st02,st03,st04,st05,jlessCur,jtfCurLess,tf01,tf02,tf03,tf04,tf05);
                try{
                    Thread.sleep(100);
                } catch (InterruptedException ex) {
                    Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                slc.start();
            }
        }else{
            st04.stop();
            st04 = new sTimer(jl02,Integer.parseInt(jtm02.getText()),Integer.parseInt(jts02.getText()));
            slc.close();
            if(checkIfSomeoneIsRunning()){
                slc = new startLessChecker(st01,st02,st03,st04,st05,jlessCur,jtfCurLess,tf01,tf02,tf03,tf04,tf05);
                slc.start();
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tf05MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf05MouseEntered
        // TODO add your handling code here:
        this.setSize(this.width,this.height);
    }//GEN-LAST:event_tf05MouseEntered

    private void jtm05FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtm05FocusLost
        // TODO add your handling code here:
        if(!st05.isRunnig()){
            st05.stop();
            st05 = new sTimer(jl05,Integer.parseInt(jtm05.getText()),Integer.parseInt(jts05.getText()));
        }
    }//GEN-LAST:event_jtm05FocusLost

    private void jtm05MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtm05MouseEntered
        // TODO add your handling code here:
        this.setSize(this.width,this.height);
    }//GEN-LAST:event_jtm05MouseEntered

    private void jts05MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jts05MouseEntered
        // TODO add your handling code here:
        this.setSize(this.width,this.height);
    }//GEN-LAST:event_jts05MouseEntered

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        // TODO add your handling code here:
        this.setSize(this.width,this.height);
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(!st05.isRunnig()){
            st05.start();
            if(!slc.isRunning()){
                slc = new startLessChecker(st01,st02,st03,st04,st05,jlessCur,jtfCurLess,tf01,tf02,tf03,tf04,tf05);
                slc.start();
            }else{
                slc.close();
                slc = new startLessChecker(st01,st02,st03,st04,st05,jlessCur,jtfCurLess,tf01,tf02,tf03,tf04,tf05);
                try{
                    Thread.sleep(100);
                } catch (InterruptedException ex) {
                    Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                slc.start();
            }
        }else{
            st05.stop();
            st05 = new sTimer(jl02,Integer.parseInt(jtm02.getText()),Integer.parseInt(jts02.getText()));
            slc.close();
            if(checkIfSomeoneIsRunning()){
                slc = new startLessChecker(st01,st02,st03,st04,st05,jlessCur,jtfCurLess,tf01,tf02,tf03,tf04,tf05);
                slc.start();
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jl01;
    private javax.swing.JLabel jl02;
    private javax.swing.JLabel jl03;
    private javax.swing.JLabel jl04;
    private javax.swing.JLabel jl05;
    private javax.swing.JLabel jlessCur;
    private javax.swing.JTextField jtfCurLess;
    private javax.swing.JTextField jtm01;
    private javax.swing.JTextField jtm02;
    private javax.swing.JTextField jtm03;
    private javax.swing.JTextField jtm04;
    private javax.swing.JTextField jtm05;
    private javax.swing.JTextField jts01;
    private javax.swing.JTextField jts02;
    private javax.swing.JTextField jts03;
    private javax.swing.JTextField jts04;
    private javax.swing.JTextField jts05;
    private javax.swing.JTextField tf01;
    private javax.swing.JTextField tf02;
    private javax.swing.JTextField tf03;
    private javax.swing.JTextField tf04;
    private javax.swing.JTextField tf05;
    // End of variables declaration//GEN-END:variables

    private void setupTimer(){
        slc = new startLessChecker();
        st01 = new sTimer(jl01,Integer.parseInt(jtm01.getText()),Integer.parseInt(jts01.getText()));
        st02 = new sTimer(jl02,Integer.parseInt(jtm02.getText()),Integer.parseInt(jts02.getText()));
        st03 = new sTimer(jl03,Integer.parseInt(jtm03.getText()),Integer.parseInt(jts03.getText()));
        st04 = new sTimer(jl04,Integer.parseInt(jtm04.getText()),Integer.parseInt(jts04.getText()));
        st05 = new sTimer(jl05,Integer.parseInt(jtm05.getText()),Integer.parseInt(jts05.getText()));
    }
    
    private boolean checkIfSomeoneIsRunning(){
        return st01.isRunnig() || st02.isRunnig() || st03.isRunnig() || st04.isRunnig() || st05.isRunnig();
    }
}

